
-- -----------------------------------------------------
-- Schema EINSTEIN_AGENDA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EINSTEIN_AGENDA` DEFAULT CHARACTER SET utf8 ;
USE `EINSTEIN_AGENDA` ;

-- -----------------------------------------------------
-- Table `EINSTEIN_AGENDA`.`PATIENTS_PHONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EINSTEIN_AGENDA`.`PATIENTS_PHONES` (
  `ID` INT NOT NULL,
  `LANDLINE_NUMBER` VARCHAR(13) NULL,
  `COMERCIAL_PHONE_NUMBER` VARCHAR(13) NULL,
  `MOB_PHONE_NUMBER` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EINSTEIN_AGENDA`.`PATIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EINSTEIN_AGENDA`.`PATIENTS` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `RG` VARCHAR(12) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `ID_PATIENT_CONTACT` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `RG_UNIQUE` (`RG` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `ID_PACIENTE_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_PACIENTES_CONTATO_PACIENTE_idx` (`ID_PATIENT_CONTACT` ASC) VISIBLE,
  CONSTRAINT `fk_PACIENTES_CONTATO_PACIENTE`
    FOREIGN KEY (`ID_PATIENT_CONTACT`)
    REFERENCES `EINSTEIN_AGENDA`.`PATIENTS_PHONES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EINSTEIN_AGENDA`.`DOCTORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EINSTEIN_AGENDA`.`DOCTORS` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `CRM` VARCHAR(13) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `SPECIALTY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CRM_UNIQUE` (`CRM` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EINSTEIN_AGENDA`.`SCHEDULINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EINSTEIN_AGENDA`.`SCHEDULINGS` (
  `ID` INT NOT NULL,
  `DATE` DATE NOT NULL,
  `TIME` TIME NOT NULL,
  `ID_PATIENT` INT NULL,
  `ID_DOCTOR` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_AGENDAMENTOS_PACIENTES1_idx` (`ID_PATIENT` ASC) VISIBLE,
  INDEX `fk_AGENDAMENTOS_MEDICOS1_idx` (`ID_DOCTOR` ASC) VISIBLE,
  CONSTRAINT `fk_AGENDAMENTOS_PACIENTES1`
    FOREIGN KEY (`ID_PATIENT`)
    REFERENCES `EINSTEIN_AGENDA`.`PATIENTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDAMENTOS_MEDICOS1`
    FOREIGN KEY (`ID_DOCTOR`)
    REFERENCES `EINSTEIN_AGENDA`.`DOCTORS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
